In [2]:
import sys
import numpy as np

In [3]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [4]:
a = np.array([1, 2, 3, 4])

In [5]:
b = np.array([0, .5, 1, 1.5, 2])

In [6]:
a[0], a[1]

(1, 2)

In [7]:
a[0:]

array([1, 2, 3, 4])

In [8]:
a[1:3]

array([2, 3])

In [9]:
a[1:-1]

array([2, 3])

In [10]:
a[::2]

array([1, 3])

*multiindexing*

In [11]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [12]:
b[[0, 2, -1]]

array([0., 1., 2.])

## Array Types

In [13]:
a

array([1, 2, 3, 4])

In [14]:
a.dtype

dtype('int32')

In [15]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [16]:
b.dtype

dtype('float64')

In [17]:
np.array([1, 2, 3, 4], dtype="float")

array([1., 2., 3., 4.])

In [18]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [19]:
c = np.array(['a', 'b', 'c'])

In [20]:
c.dtype

dtype('<U1')

In [21]:
d = np.array([{'a':1}, sys])

In [22]:
d.dtype

dtype('O')

## Dimensions and Shapes

In [23]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [24]:
A.shape

(2, 3)

In [25]:
A.ndim

2

In [26]:
A.size

6

In [27]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])
             
    

In [28]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [29]:
B.shape

(2, 2, 3)

In [30]:
B.ndim

3

In [31]:
B.size

12

In [32]:
B.dtype

dtype('int32')

If the shape isn't consistent, it'll jst fall back to regular Python Objects:

In [33]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
C.dtype

In [ ]:
C.size

## Indexing and Slicing of Matrices

In [128]:
# Square Matrix
A = np.array([
#    0. 1. 2
    [1, 2, 3], #0
    [4, 5, 6], #1
    [7, 8, 9]  #2
])

In [129]:
A[1]

array([4, 5, 6])

In [130]:
A[1][0]

4

In [131]:
# A[d1, d2, d3, d4]

In [132]:
A[1, 0]

4

In [133]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [134]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [138]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [136]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

modifying array:

In [ ]:
A[1] = np.array([10, 10, 10])

In [ ]:
A

In [ ]:
#expand operation
A[2] = 99


In [ ]:
A

## Summary Statistics

In [ ]:
a = np.array([1, 2, 3, 4])

In [ ]:
a.sum()

In [ ]:
a.mean()

In [ ]:
a.std()

In [ ]:
a.var()

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:
A.sum()

In [ ]:
A.mean()

In [ ]:
A.std()

In [ ]:
A.sum(axis=0)

In [ ]:
A.sum(axis=1)

In [ ]:
A.mean(axis=0)

In [ ]:
A.mean(axis=1)

In [ ]:
A.std(axis=0)

In [ ]:
A.std(axis=1)

## Broadcasting and Vectorized operations

In [ ]:
a = np.arange(4)

In [ ]:
a

In [ ]:
a + 10

In [ ]:
a * 10

In [ ]:
a

In [ ]:
a += 100

In [ ]:
a

In [ ]:
l = [0, 1, 2, 3]

In [ ]:
[i * 10 for i in l]

In [ ]:
a = np.arange(4)

In [ ]:
a

In [ ]:
b = np.array([10, 10, 10, 10])

In [ ]:
b

In [ ]:
a + b

## Boolean Arrays

_(Also called masks)_

In [ ]:
a = np.arange(4)

In [ ]:
a

In [ ]:
a[[0,-1]]

In [ ]:
a[0], a[-1]

In [ ]:
a[[True, False, False, True]]

In [ ]:
a * 10

In [ ]:
a

In [ ]:
a >= 2

In [ ]:
a[a >= 2]

In [ ]:
a.mean()

In [ ]:
a[a > a.mean()]

In [ ]:
a[~(a > a.mean())]

In [ ]:
a[(a == 0) | (a == 1)]

In [ ]:
a[(a <= 2) & (a % 2 == 0)]

In [ ]:
A = np.random.randint(100, size=(3, 3))

In [ ]:
A

In [ ]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

In [ ]:
A

In [ ]:
A > 30

In [ ]:
A[A > 30]

## Linear Algebra

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [ ]:
A.dot(B)

In [ ]:
A.dot(B) #dot product

In [ ]:
A @ B #cross product

In [ ]:
B.T #Transpose

In [ ]:
B.T @ A

## Size of Objects in Memory

### Int, Floats

In [34]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [35]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [40]:
# Numpy size is much smaller
np.dtype(int).itemsize

4

In [41]:
np.dtype(np.int8).itemsize

1

In [42]:
np.dtype(float).itemsize

8

### Lists are even larger

In [43]:
# A one-element list
sys.getsizeof([1])

64

In [116]:
np.array([1]).nbytes

4

### And performance is also important

In [55]:
l = list(range(100000))

In [56]:
a = np.arange(100000)

In [57]:
%time np.sum(a ** 2)

CPU times: total: 0 ns
Wall time: 955 µs


216474736

In [58]:
%time sum([x ** 2 for x in l])

CPU times: total: 15.6 ms
Wall time: 15.4 ms


333328333350000

## Use Numpy Functions

### random

In [61]:
np.random.random(size=2)

array([0.25475786, 0.92758673])

In [62]:
np.random.normal(size=2)

array([-0.21587439,  0.10657389])

In [63]:
np.random.rand(2, 4)

array([[0.38356155, 0.98468608, 0.1357572 , 0.36078046],
       [0.25815228, 0.86031647, 0.7110232 , 0.17227182]])

### arange

In [64]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [66]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

### reshape

In [67]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [68]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

### linspace

In [70]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [71]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [72]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

### zeros, ones, empty

In [75]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [76]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [99]:
np.zeros((3,3), dtype=np.int32)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [100]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [101]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [102]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [103]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

### identity and eye

In [107]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [108]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [109]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [110]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])