In [2]:
import sys
import numpy as np

In [3]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [4]:
a = np.array([1, 2, 3, 4])

In [5]:
b = np.array([0, .5, 1, 1.5, 2])

In [6]:
a[0], a[1]

(1, 2)

In [7]:
a[0:]

array([1, 2, 3, 4])

In [8]:
a[1:3]

array([2, 3])

In [9]:
a[1:-1]

array([2, 3])

In [10]:
a[::2]

array([1, 3])

*multiindexing*

In [12]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [13]:
b[[0, 2, -1]]

array([0., 1., 2.])

**Array Types**

In [14]:
a

array([1, 2, 3, 4])

In [15]:
a.dtype

dtype('int32')

In [16]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [17]:
b.dtype

dtype('float64')

In [29]:
np.array([1, 2, 3, 4], dtype="float")

array([1., 2., 3., 4.])

In [31]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [32]:
c = np.array(['a', 'b', 'c'])

In [33]:
c.dtype

dtype('<U1')

In [34]:
d = np.array([{'a':1}, sys])

In [35]:
d.dtype

dtype('O')

**Dimensions and Shapes**

In [36]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [37]:
A.shape

(2, 3)

In [39]:
A.ndim

2

In [40]:
A.size

6

In [41]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])
             
    

In [42]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [43]:
B.shape

(2, 2, 3)

In [46]:
B.ndim

3

In [47]:
B.size

12

In [48]:
B.dtype

dtype('int32')