In [10]:
import sys
import numpy as np

In [11]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [12]:
a = np.array([1, 2, 3, 4])

In [13]:
b = np.array([0, .5, 1, 1.5, 2])

In [14]:
a[0], a[1]

(1, 2)

In [15]:
a[0:]

array([1, 2, 3, 4])

In [16]:
a[1:3]

array([2, 3])

In [17]:
a[1:-1]

array([2, 3])

In [18]:
a[::2]

array([1, 3])

*multiindexing*

In [19]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [20]:
b[[0, 2, -1]]

array([0., 1., 2.])

## Array Types

In [21]:
a

array([1, 2, 3, 4])

In [22]:
a.dtype

dtype('int32')

In [23]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [24]:
b.dtype

dtype('float64')

In [25]:
np.array([1, 2, 3, 4], dtype="float")

array([1., 2., 3., 4.])

In [26]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [27]:
c = np.array(['a', 'b', 'c'])

In [28]:
c.dtype

dtype('<U1')

In [29]:
d = np.array([{'a':1}, sys])

In [30]:
d.dtype

dtype('O')

## Dimensions and Shapes

In [31]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [32]:
A.shape

(2, 3)

In [33]:
A.ndim

2

In [34]:
A.size

6

In [35]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])
             
    

In [36]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [37]:
B.shape

(2, 2, 3)

In [38]:
B.ndim

3

In [39]:
B.size

12

In [40]:
B.dtype

dtype('int32')

If the shape isn't consistent, it'll jst fall back to regular Python Objects:

In [42]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [44]:
C.dtype

NameError: name 'C' is not defined

In [45]:
C.size

NameError: name 'C' is not defined

## Indexing and Slicing of Matrices

In [63]:
# Square Matrix
A = np.array([
#    0. 1. 2
    [1, 2, 3], #0
    [4, 5, 6], #1
    [7, 8, 9]  #2
])

In [64]:
A[1]

array([4, 5, 6])

In [65]:
A[1][0]

4

In [66]:
# A[d1, d2, d3, d4]

In [67]:
A[1, 0]

4

In [68]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [70]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [71]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

modifying array:

In [72]:
A[1] = np.array([10, 10, 10])

In [73]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [74]:
#expand operation
A[2] = 99


In [75]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])