# Load in Numpy (remember to pip instal numpy first)

In [1]:
import numpy as np
import sys

## The Basics

In [2]:
a = np.array([1, 2, 3], dtype='int32')
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Get Dimension
print(a.ndim)
print(b.ndim)

1
2


In [5]:
# Get shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [6]:
# Get Type
a.dtype

dtype('int32')

In [7]:
# Get size

In [8]:
# Get Size
a.itemsize

4

In [9]:
# Get total size
print(a.size * a.itemsize)
#or
print(a.nbytes)

12
12


## Accessing/Changing specific elements, rows, columns, etc

In [10]:

a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
a.shape

(2, 7)

In [12]:
# Get a specific element [r, c] 
a[1, 5]

13

In [13]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
# Get a specific column
a[: ,2]

array([ 3, 10])

In [15]:
# Getting a little more fancy [staringindex:endindex:stepsize]
a[0,1:6:2]


array([2, 4, 6])

In [16]:
# modify
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [17]:
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [18]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


### 3-D example

In [19]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [20]:
# Get specific element (work outside in)
b[0,0:2,0:2]

array([[1, 2],
       [3, 4]])

In [21]:
# replace
b[:,1,:] = [[9,9], [8,8]] 

In [22]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

## Initializing Different Types of Arrays

In [32]:
# All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [33]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [34]:
np.zeros((5,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])