## Load in Numpy (remember to pip instal numpy first)

In [2]:
import numpy as np
import sys

## The Basics

In [19]:
a = np.array([1, 2, 3], dtype='int32')
print(a)

[1 2 3]


In [5]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [8]:
# Get Dimension
print(a.ndim)
print(b.ndim)

1
2


In [11]:
# Get shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [16]:
# Get Type
a.dtype

dtype('int16')

In [17]:
# Get size

In [27]:
# Get Size
a.itemsize

4

In [29]:
# Get total size
print(a.size * a.itemsize)
#or
print(a.nbytes)

12
12
